In [1]:
print("Hello from jupyter notebook!")

Hello from jupyter notebook!


In [2]:
import numpy as np

In [4]:
#1
l = [1,2,3]
print(sum(l)) # python function
print(np.sum(l)) # Numpy function

6
6


In [6]:
#2
l1 = np.arange(1,3000000)
%time l1 + 6


Wall time: 16 ms


array([      7,       8,       9, ..., 3000003, 3000004, 3000005])

In [7]:
#3
# l1 = np.arange(1,13).reshape((4,3))
# l1 = np.arange(1,13).reshape((3,4))
# l1 = np.arange(1,13).reshape((2,6))
# l1 = np.arange(1,13).reshape((6,2))
# l1 = np.arange(1,13).reshape((12,1))

l1 = np.arange(1,13).reshape((6,-1))

print(l1)
print("Diminsion:", l1.ndim)
print("Type:", l1.dtype)
print("Size:", l1.size)
print("Itemsize:", l1.itemsize)
print("Shape:", l1.shape)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]
Diminsion: 2
Type: int32
Size: 12
Itemsize: 4
Shape: (6, 2)


In [9]:
#4
l1 = np.arange(1000)
%time l1 + 6

Wall time: 0 ns


array([   6,    7,    8,    9,   10,   11,   12,   13,   14,   15,   16,
         17,   18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
         28,   29,   30,   31,   32,   33,   34,   35,   36,   37,   38,
         39,   40,   41,   42,   43,   44,   45,   46,   47,   48,   49,
         50,   51,   52,   53,   54,   55,   56,   57,   58,   59,   60,
         61,   62,   63,   64,   65,   66,   67,   68,   69,   70,   71,
         72,   73,   74,   75,   76,   77,   78,   79,   80,   81,   82,
         83,   84,   85,   86,   87,   88,   89,   90,   91,   92,   93,
         94,   95,   96,   97,   98,   99,  100,  101,  102,  103,  104,
        105,  106,  107,  108,  109,  110,  111,  112,  113,  114,  115,
        116,  117,  118,  119,  120,  121,  122,  123,  124,  125,  126,
        127,  128,  129,  130,  131,  132,  133,  134,  135,  136,  137,
        138,  139,  140,  141,  142,  143,  144,  145,  146,  147,  148,
        149,  150,  151,  152,  153,  154,  155,  1

In [10]:
#5
#5
print("Type:", l1.dtype)

Type: int32


In [11]:
#6
print("Size:", l1.size)

Size: 1000


In [12]:
#7
print("Itemsize:", l1.itemsize)

Itemsize: 4


In [13]:
#8
print("Shape:", l1.shape)

Shape: (1000,)


In [14]:
#9
print(l)

[1, 2, 3]


In [16]:
#10
l1 = np.arange(1,13).reshape((3,4))
print(l1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [19]:
#11

l1 = np.random.randn(3,3,3)

print(l1)

[[[ 0.43664886  1.78871535  1.58308164]
  [ 0.82325731  0.93288727 -1.29354528]
  [ 0.09359104 -0.9010126  -0.35703125]]

 [[ 1.14037246  1.12839132  0.91967665]
  [-1.64440603  1.66383872 -0.76582602]
  [ 0.20540197 -0.28887078 -0.47481967]]

 [[-0.15542794  0.62027934  0.63520079]
  [-2.75271263  1.05152493  0.76941651]
  [-0.31644585  0.27751034 -0.76623144]]]


In [20]:
#12
l1 * 2

array([[[ 0.87329771,  3.5774307 ,  3.16616328],
        [ 1.64651463,  1.86577454, -2.58709057],
        [ 0.18718207, -1.8020252 , -0.71406249]],

       [[ 2.28074491,  2.25678263,  1.8393533 ],
        [-3.28881206,  3.32767744, -1.53165204],
        [ 0.41080394, -0.57774155, -0.94963934]],

       [[-0.31085589,  1.24055868,  1.27040158],
        [-5.50542527,  2.10304987,  1.53883302],
        [-0.63289171,  0.55502069, -1.53246288]]])

In [21]:
#13
l1 + 2


array([[[ 2.43664886,  3.78871535,  3.58308164],
        [ 2.82325731,  2.93288727,  0.70645472],
        [ 2.09359104,  1.0989874 ,  1.64296875]],

       [[ 3.14037246,  3.12839132,  2.91967665],
        [ 0.35559397,  3.66383872,  1.23417398],
        [ 2.20540197,  1.71112922,  1.52518033]],

       [[ 1.84457206,  2.62027934,  2.63520079],
        [-0.75271263,  3.05152493,  2.76941651],
        [ 1.68355415,  2.27751034,  1.23376856]]])

In [22]:
#14
print(type(l1))

<class 'numpy.ndarray'>


In [43]:
#15
np.zeros((8,8))

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [25]:
#16
a = np.array([6,8])
a.itemsize

4

In [26]:
#17

a.shape

(2,)

In [27]:
#18

np.zeros((a.shape))

array([0., 0.])

In [28]:
#19
np.zeros_like(a)


array([0, 0])

In [29]:
#20

np.zeros_like(a)


array([0, 0])

In [42]:
#21
b = np.ones((3,6))
b

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [31]:
#22
b = np.ones_like(a)
b

array([1, 1])

In [41]:
#23
b = np.ones_like(a) * 10 
b

array([10, 10])

In [40]:
#24
b = np.full((8,8), 10)
b

array([[10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10]])

In [37]:
#25
b = np.full_like(a, 6)
b

array([6, 6])

In [39]:
#26
np.empty((5,9))

array([[1.44106129e+218, 9.02785337e+271, 1.68916619e+155,
        3.17095856e+180, 3.15582783e+161, 6.01334639e-154,
        2.58742259e+161, 2.31634000e-152, 1.43985015e+132],
       [5.87774051e+135, 2.31705313e+251, 7.04378520e+199,
        1.47039297e+224, 7.22764231e+159, 1.91002772e+227,
        2.13945649e+161, 2.97401042e+222, 2.06999331e+161],
       [6.51880068e+265, 4.81809028e+233, 2.35345430e+251,
        1.41442058e+190, 4.45197005e+252, 5.98129759e-154,
        3.80985847e+180, 6.01334668e-154, 4.47593816e-091],
       [6.01346953e-154, 2.59345432e+161, 2.46089539e-154,
        7.77661508e+160, 2.43194431e-152, 1.46922215e+195,
        5.59121949e+252, 4.82407136e+228, 4.72883470e+164],
       [9.82390921e+252, 6.01334434e-154, 1.06441859e+248,
        4.47590761e-091, 6.01334512e-154, 1.43615024e+161,
        6.01334682e-154, 1.27731744e-152, 8.73972593e+183]])

In [36]:
#27
np.empty_like(a)

array([ 436183188, 1072938372])

In [44]:
#28

np.full(a.shape, np.nan)

array([nan, nan])

In [46]:
#29
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])

In [47]:
#30
np.identity(12)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [48]:
#31

a = np.array([1,2,5], dtype=int)

a.dtype


dtype('int32')

In [49]:
#32
b = np.array([3,6,7], dtype=a.dtype)
b.dtype

dtype('int32')

In [54]:
#33

a = np.arange(1,28).reshape((3,3,3))
a

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [55]:
#34
a % 8 == 0

array([[[False, False, False],
        [False, False, False],
        [False,  True, False]],

       [[False, False, False],
        [False, False, False],
        [ True, False, False]],

       [[False, False, False],
        [False, False,  True],
        [False, False, False]]])

In [56]:
#35
a.T

array([[[ 1, 10, 19],
        [ 4, 13, 22],
        [ 7, 16, 25]],

       [[ 2, 11, 20],
        [ 5, 14, 23],
        [ 8, 17, 26]],

       [[ 3, 12, 21],
        [ 6, 15, 24],
        [ 9, 18, 27]]])

In [57]:
#36
a.T.T.T.T

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [58]:
#37
a = np.array([-5,18,10,-2,-34,20])
np.round(a)

array([ -5,  18,  10,  -2, -34,  20])

In [59]:
#38
a = np.array([-5,18,10,-2,-34,20])
np.floor(a)

array([ -5.,  18.,  10.,  -2., -34.,  20.])

In [60]:
#39
a = np.array([-5,18,10,-2,-34,20])
np.ceil(a)

array([ -5.,  18.,  10.,  -2., -34.,  20.])

In [61]:
#40
a = np.array([-5,18,10,-2,-34,20])
np.exp(a)

array([6.73794700e-03, 6.56599691e+07, 2.20264658e+04, 1.35335283e-01,
       1.71390843e-15, 4.85165195e+08])

In [62]:
#41
a = np.array([-5,18,10,-2,-34,20])
np.square(a)

array([  25,  324,  100,    4, 1156,  400], dtype=int32)

In [63]:
#42
a = np.array([-5,18,10,-2,-34,20])
np.fabs(a)

array([ 5., 18., 10.,  2., 34., 20.])

In [64]:
#43
a = np.array([-5,18,10,-2,-34,20])
np.abs(a)

array([ 5, 18, 10,  2, 34, 20])

In [67]:
#44
a.transpose()

array([ -5,  18,  10,  -2, -34,  20])

In [68]:
#45
a % 3 == 0

array([False,  True, False, False, False, False])

In [69]:
#46
a = np.array([1,3,4], dtype='int')
a.dtype

dtype('int32')

In [70]:
#47
names = np.array(["Qasim","Hamza","Junaid","Ali","Qasim","Abid"])

data = np.random.randn(6,4)
print(names, data, sep="\n\n\n")
# print(names=="Qasim")
# print(names=="Ali")
# print((names=="Qasim") | (names=="Ali"))
data[(names=="Qasim") |  (names=="Ali")][:,[0,-1]]

['Qasim' 'Hamza' 'Junaid' 'Ali' 'Qasim' 'Abid']


[[ 0.63624704 -0.5018275   0.11056425 -0.47191423]
 [-0.38118935 -0.35028213 -1.36089463  1.82550598]
 [ 1.54090283 -1.52071689  0.6885197  -0.33486555]
 [ 1.24746144  0.97834327 -0.85311148 -0.2720515 ]
 [ 0.59892852 -0.24176903  0.05446996  0.82581905]
 [ 1.33838916  0.72877519 -0.58525633 -0.28248374]]


array([[ 0.63624704, -0.47191423],
       [ 1.24746144, -0.2720515 ],
       [ 0.59892852,  0.82581905]])

In [71]:
#48
l = [1,3,5,3,5]
l[:3]
l[0] = 5
l

[5, 3, 5, 3, 5]

In [72]:
#49
a = np.arange(8*4).reshape((8,4))
print(a)

for i in range(len(a)):
    a[i] = i
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]
[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]]


In [73]:
#50
a = np.arange(10,3*3*3+10).reshape(3,3,3)
print(a)
a[[2,0,1]]


[[[10 11 12]
  [13 14 15]
  [16 17 18]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]

 [[28 29 30]
  [31 32 33]
  [34 35 36]]]


array([[[28, 29, 30],
        [31, 32, 33],
        [34, 35, 36]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])